bicho/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('tabela/', include('tabela.urls')),
    path('admin/', admin.site.urls),
]

tabela/urls.py
from django.urls import path
from . import views

app_name = 'bicho'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:grupo_id>/', views.detail, name='detail'),
  path('<int:grupo_id>/result/', views.result, name='result'),
  path('<int:grupo_id>/vote/', views.vote, name='vote'),  
]

tabela/models.py
from django.db import models

# Create your models here.

class Grupo(models.Model):
  numero = models.IntegerField(default=0)
  nome = models.CharField(max_length=100)
  imagem = models.CharField(max_length=255)
  
  def __str__(self):
    return self.nome
  
class Bicho(models.Model):
  grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)
  numero = models.IntegerField(default=0)

  def __str__(self):
    return "%d" % self.numero

tabela/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader

from django.views import generic

from .models import Grupo, Bicho

# Create your views here.

class IndexView(generic.ListView):
  template_name = 'tabela/index.html'
  context_object_name = 'grupo_list'
  
  def get_queryset(self):
    return Grupo.objects.order_by('numero')
  
def index(request):
  grupos = Grupo.objects.all()
  lista_grupos = []
  item = []
  ii=0
  for g in grupos:
    ii+=1

    if ii < 6:
      item.append(g)
    else:
      lista_grupos.append(item)
      item = [g]
      ii=1
  lista_grupos.append(item)
    
  tpl = loader.get_template('tabela/index.html')
  context = {
    'grupo_list': lista_grupos,
  }
  return HttpResponse(tpl.render(context,request))
  
def detail(request,grupo_id):
  try:
    grupo = Grupo.objects.get(numero=grupo_id)
    numeros = Bicho.objects.filter(grupo = grupo.id)
  except Grupo.DoesNotExist:
    raise Http404("Grupo nao existe")
  
  #import pdb;pdb.set_trace()
  return render(request, 'tabela/detail.html', {'grupo': grupo, 'numeros': numeros})
  
def result(request,grupo_id):
  return HttpResponse('vc esta vendo os resultados do grupo %d' % grupo_id)
  
def vote(request,grupo_id):
  grupo = get_object_or_404(Grupo,numero=grupo_id)
  try:
    numero_choice = Bicho.objects.get(numero=request.POST['numero'])
  except (KeyError, Bicho.DoesNotExist):
    return render(request, 'tabela/detail.html', {
      'grupo': grupo,
      'error_message': 'Vc nao selecionou uma opcao'
    })    
  return HttpResponse('Vc esta votando no grupo %s' % grupo_id)
  

tabela/templates/tabela/detail.html
{% extends "main.html" %}

{% block title1 %}Grupo {{ grupo }} {% endblock %}

{% block content %}

{% if grupo %}


{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'bicho:vote' grupo.id %}" method="post">
{% csrf_token %}
{% if numeros %}
	{%for n in numeros%}
	  <input type="radio" name="numero" id="numero{{forloop.counter}}" value="{{n.numero}}"><label>{{n.numero}}</label><br>
	{%endfor%}
{% endif %}
<input type="submit" value="votar"/>
</form>

{% endif %}
{% endblock %}

tabela/templates/tabela/index.html
{% extends "main.html" %}
{% load static %}

{% block title1 %} Grupos {% endblock %}

{% block content %}
{% if grupo_list %}
  <table width="100%" align="center">
  {% for g in grupo_list %}
    <tr>
	{% for x in g %}
	  <td><a href="{% url 'bicho:index' %}{{x.id}}"><img src="{% static x.imagem %}"/></a></td>
	{% endfor %}
	</tr>
  {% endfor %}
  
  </table>
{% else %}
  <p>Sem grupos para exibir</p>
{% endif %}

{% endblock %}